config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :passwords => "devise/passwords",
                                       :omniauth_callbacks => "devise/omniauth_callbacks"}
  root 'posts#index'
  resources :posts

  namespace :api do
    namespace :v1 do
      post 'user_auths/user_sign_up' => 'user_auths#user_sign_up', defaults: {format: 'json'}
      post 'user_auths/user_sign_in' => 'user_auths#user_sign_in', defaults: {format: 'json'}
      post 'user_posts/create_post' => 'user_posts#create_post', defaults: {format: 'json'}
      get 'user_posts/show_post' => 'user_posts#show_post', defaults: {format: 'json'}
      get 'user_posts/delete_post' => 'user_posts#delete_post', defaults: {format: 'json'}
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :photos, :as => :imageable, dependent: :destroy
  accepts_nested_attributes_for :photos

  validates_presence_of :post_text, :is_public
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  private

  def post_params
   params.require(:post).permit(:post_text, :is_public, photos_attributes: [:image])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for @post, :html => { :multipart => true } do |f|
  .field
    = f.label :title
    %br/
    = f.text_field :post_text
  .field
    = f.label :Is_public
    %br/
    = f.label :Yes
    = f.radio_button :is_public, "1"
    = f.label :No
    = f.radio_button :is_public, "0"
  %div
    Upload Image
    = f.fields_for :photos do |ph|
      = ph.file_field :image
  .actions
    = f.submit

app/views/posts/edit.html.haml
= render :partial => 'form'

app/views/posts/index.html.haml
= link_to new_post_path, :class => "new_post" do
  New Post
= link_to 'Logout', destroy_user_session_path, :method => :delete, :class => 'logout'
%table{:border => "1"}
  %h1 List of Posts
  %tr
    %th Post
    %th Is Public
    %th Image
  - @posts.each do |post|
    %tr
      %td= post.post_text
      %td= post.is_public
      %td= image_tag Photo.find_by_imageable_id(post.id).image.url(:small)
      %td= link_to 'Show', post_path(post)
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post_path(post),
                    method: :delete, data: { confirm: 'Are you sure?' }
:css
  .logout{margin-left: 1251px;
    font-size: 23px;
  }
  .new_post{font-size: 23px;}

app/views/posts/new.html.haml
= render :partial => 'form'

app/views/posts/show.html.haml
%p
  %strong Post:
  = @post.post_text
%p
  %strong Is Public:
  = @post.is_public
%p
  %strong Image:
  = image_tag Photo.find_by_imageable_id(@post.id).image.url(:small)